// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_lblMsg = NULL;
lv_obj_t * ui_btnPay = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMsg = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMsg, -15);
    lv_obj_set_y(ui_lblMsg, -98);
    lv_obj_set_align(ui_lblMsg, LV_ALIGN_CENTER);

    ui_btnPay = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnPay, 100);
    lv_obj_set_height(ui_btnPay, 50);
    lv_obj_set_x(ui_btnPay, -8);
    lv_obj_set_y(ui_btnPay, -33);
    lv_obj_set_align(ui_btnPay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_lblMsg = NULL;
    ui_btnPay = NULL;

}
